### ISSUE TITLE
Catching errors on the client

### ISSUE THREAD

**Issue by scf4** [thebigredgeek/apollo-errors#13]
Where are **query** errors supposed to be caught on the client?

I throw a `NotFoundError` on the server if an item can't be found. The error info can be accessed in `props.data.error`, but it still results in an uncaught exception. 

I might be missing something fairly simple, but the apollo docs are pretty light when it comes to error handling!

**Comment by thebigredgeek** [comment]
I think it really depends on your own use case.  For me, I use Redux middleware to push the errors into a separate store namespace.  This works because I pass a nonce, by default, with every request so I can easily associate errors with the query/mutation/subscription that generated them.  Then I can just connect the errors as such to whatever container made the request via a HoC

**Comment by scf4** [comment]
Hey thanks for the response. Perhaps I misunderstood, but my problem is not so much the handling of errors and dealing with them in UI, but rather the fundamentals of catching them (to prevent an uncaught exception) in the first place. 

With mutations you can use try/catch blocks, but with queries and the react-apollo HoC where can that go? For some reason I was under the impression that accessing the data.error property would prevent an uncaught exception coming from the HoC but that doesn't seem to be the case?
