### ISSUE TITLE
Reasoning behind the two-step error pattern?

### ISSUE THREAD

**Issue by SachaG** [thebigredgeek/apollo-errors#43]
The "normal" way to use this package is:

```
import { createError } from 'apollo-errors';

const FooError = createError('FooError', { message: 'A foo error has occurred' });

throw new FooError({ data: { something: 'important' } });
```

However, that seems a bit cumbersome to me. Is there a reason why the API doesn't look something like this instead?

```
import { ApolloError } from 'apollo-errors';

throw new ApolloError({ name: 'FooError', message: 'A foo error has occurred', data: { ... } });
```

**Comment by ayoubice** [comment]
@SachaG: Theoretically, you can use ApolloError class. `createError` it only binds to ApolloError class.
https://github.com/thebigredgeek/apollo-errors/blob/181c105cc9d48778a5842dc4fdeb5eb567b95647/src/index.ts#L92

On my use case, I am using it to format errors
```
if( e instanceof FooError) {
  // Do some formating of FooError
}
```

**Comment by alex-dixon** [comment]
@SachaG It seems possible to get the error you threw via the `originalError` property on the error passed to `formatError`. So you can create errors however you like and if you're concerned about finding them there you go.

Since I installed this lib thinking it was necessary to get information from my custom errors I might just stick with this which gets around the problem you're describing somewhat:
```
const exInfo = (msg: string, map: object) => {
  const ex = createError("ex-info", { message: msg })
  throw new ex({ data: map })
}
```

**Comment by thebigredgeek** [comment]
If you only throw `ApolloError`, you can't use `instanceof`.  That was my main reasoning for the `two step` process.  It's usually best to throw typed errors imho
